/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.avanceproyecto.view;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Pablo Tello
 */
public class INICIO extends javax.swing.JFrame {
    private static final Logger logger = LoggerFactory.getLogger(INICIO.class);

    /**
     * Creates new form INICIO
     */
    public INICIO() {
        initComponents();
        // Hacer que la ventana inicie maximizada
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        // Configurar el layout para que el desktopPane ocupe todo el espacio
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(desktopPane, BorderLayout.CENTER);
        
        // Dar color de fondo al desktopPane (opcional)
        desktopPane.setBackground(new Color(240, 240, 240));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        alojamientoMenuItem = new javax.swing.JMenuItem(); // Nuevo item para alojamiento
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("SISRESERVA");
        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("ARCHIVO");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("HABITACIONES");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("SERVICIO");
        editMenu.add(copyMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("RESERVA");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("CONSUMO DE SERVICIOS"); // Cambiar nombre
        helpMenu.add(contentMenuItem);

        alojamientoMenuItem.setMnemonic('l');
        alojamientoMenuItem.setText("ALOJAMIENTOS"); // Nuevo item
        helpMenu.add(alojamientoMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("CLIENTES");
        helpMenu.add(aboutMenuItem);

        jMenuItem1.setText("PAGOS");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem1);

        menuBar.add(helpMenu);

        jMenu1.setText("CONSULTAS");
        menuBar.add(jMenu1);

        jMenu2.setText("CONFIGURACIONES");

        jMenuItem2.setText("USUARIOS Y ACCESOS");
        jMenu2.add(jMenuItem2);

        menuBar.add(jMenu2);

        jMenu3.setText("SALIR");
        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        // Configurar eventos del menú
        // Menú Archivo
        cutMenuItem.addActionListener(e -> {
            JInternalFrame frame = new Habitacion();
            frame.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
            desktopPane.add(frame);
            frame.setVisible(true);
            try {
                frame.setSelected(true);
            } catch (java.beans.PropertyVetoException ex) {}
        });

        copyMenuItem.addActionListener(e -> {
            Servicio frame = new Servicio();
            desktopPane.add(frame);
            frame.setVisible(true);
            try {
                frame.setSelected(true);
            } catch (java.beans.PropertyVetoException ex) {}
        });

        // Menú Reserva
        contentMenuItem.addActionListener(e -> {
            try {
                logger.info("Abriendo ventana Consumo de Servicios");
                ConsumoServicio frame = new ConsumoServicio();
                frame.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
                desktopPane.add(frame);
                frame.setVisible(true);
                frame.setSelected(true);
            } catch (Exception ex) {
                logger.error("Error al abrir ventana Consumo de Servicios", ex);
                JOptionPane.showMessageDialog(this, "Error al abrir ventana Consumo de Servicios: " + ex.getMessage());
            }
        });

        alojamientoMenuItem.addActionListener(e -> {
            try {
                logger.info("Abriendo ventana Alojamientos");
                Alojamiento frame = new Alojamiento();
                frame.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
                desktopPane.add(frame);
                frame.setVisible(true);
                frame.setSelected(true);
            } catch (Exception ex) {
                logger.error("Error al abrir ventana Alojamientos", ex);
                JOptionPane.showMessageDialog(this, "Error al abrir ventana Alojamientos: " + ex.getMessage());
            }
        });

        aboutMenuItem.addActionListener(e -> {
            try {
                logger.info("Abriendo ventana Clientes");
                Cliente frame = new Cliente();
                frame.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
                desktopPane.add(frame);
                frame.setVisible(true);
                frame.setSelected(true);
            } catch (Exception ex) {
                logger.error("Error al abrir ventana Clientes", ex);
                JOptionPane.showMessageDialog(this, "Error al abrir ventana Clientes: " + ex.getMessage());
            }
        });

        jMenuItem1.addActionListener(e -> {
            try {
                logger.info("Abriendo ventana Facturas");
                Factura frame = new Factura();
                frame.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
                desktopPane.add(frame);
                frame.setVisible(true);
                frame.setSelected(true);
            } catch (Exception ex) {
                logger.error("Error al abrir ventana Facturas", ex);
                JOptionPane.showMessageDialog(this, "Error al abrir ventana Facturas: " + ex.getMessage());
            }
        });

        // Menú Configuraciones
        jMenuItem2.addActionListener(e -> {
            new Usuario().setVisible(true); // Abre ventana Usuarios
        });

        // Menú Salir
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int option = JOptionPane.showConfirmDialog(null, 
                    "¿Desea salir del sistema?",
                    "Confirmar salida",
                    JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INICIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem alojamientoMenuItem; // Agregar nueva variable
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
